### ISSUE TITLE
Not a strongly named assembly

### ISSUE THREAD

**Issue by zealizhe** [NZSmartie/Newtonsoft.Json.Cbor#1]
In the latest version 0.3.3-alpha, Newtonsoft.Json.Cbor.dll does not represent a strongly named assembly. Could you please make one?

**Comment by NZSmartie** [comment]
Sure, will push out a new release when i get a chance to sit down

**Comment by zealizhe** [comment]
@NZSmartie Thanks for the prompt response!!! Very good project!

**Comment by zealizhe** [comment]
@NZSmartie just wonder when you can push out a new release? Thanks!

**Comment by zealizhe** [comment]
@NZSmartie any update on the new release? Thank you!

**Comment by NZSmartie** [comment]
I was investigating using the same automated build system as the official Newtonsoft.* libraries but got a little carried away. I'll push a minor release with SN signing and then focus on automating the build to save me from this hassle in the future 😁

**Comment by NZSmartie** [comment]
https://www.nuget.org/packages/Newtonsoft.Json.Cbor/ 0.3.4-alpha haas just been pushed that includes Strong Name Signed assembly. give it a few minutes and it'll be there.
